<a href="https://colab.research.google.com/github/joynaomi81/Neural-Network-BootCamp/blob/main/Loss_Functions_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



*   Mean Square Error(MSE)
*   Binary Cross Entropy (BCE)





# **MSE** **Loss** **Function**

In [ ]:
import torch
import torch.nn as nn

In [ ]:
pred = torch.randn(5,6)
label = torch.randn(5,6)

In [ ]:
# None reduction
mse = nn.MSELoss(reduction='none')
loss = mse(pred,label)
print(loss)

tensor([[ 0.1070,  0.1503,  0.1544,  1.7412, 13.1683,  1.7818],
        [ 4.5347,  3.3680,  3.4522,  0.0466, 12.2724,  0.4724],
        [ 1.5027,  0.0989,  1.5416,  0.0857,  0.1166,  1.2155],
        [ 1.9187,  0.5454,  0.3342, 10.2814,  0.0225,  6.1467],
        [ 1.8200,  4.5793,  0.4786,  0.5804,  2.3539,  0.1549]])


In [ ]:
# mean reduction
mse = nn.MSELoss(reduction='mean')
loss = mse(pred,label)
print(loss)

tensor(2.5009)


In [ ]:
# sum reduction
mse = nn.MSELoss(reduction='sum')
loss = mse(pred,label)
print(loss)

tensor(75.0262)


In [ ]:
((pred-label)**2).mean()

tensor(2.5009)

# **BCE Loss Function**

In [ ]:
pred

tensor([[-2.0487,  0.9248,  0.6982, -1.0247, -2.6492, -0.4838],
        [-0.9336,  1.0291, -0.3804,  0.0049,  1.6228, -1.5308],
        [ 1.2563, -1.0910, -1.5704,  0.2021,  0.5011,  0.7620],
        [ 0.8427,  0.4991,  0.2577,  2.0024,  1.1962, -1.2155],
        [-0.1238,  2.4212, -0.7386,  0.2814, -1.4389,  0.2190]])

In [ ]:
label = torch.zeros(5,6).random_(0,2)
label

tensor([[1., 1., 1., 0., 1., 1.],
        [1., 1., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0., 0.],
        [0., 1., 1., 0., 1., 0.],
        [0., 1., 1., 1., 0., 0.]])

In [ ]:
 sigmoid = nn.Sigmoid()

In [ ]:
BCE = nn.BCELoss(reduction = 'mean')

In [ ]:
  BCE(sigmoid(pred),label)

tensor(0.8749)

BCEWITHLogisticsLoss

In [ ]:
becs = nn.BCEWithLogitsLoss(reduction = 'mean')
becs(pred,label)

tensor(0.8749)