<a href="https://colab.research.google.com/github/joynaomi81/Neural-Network-BootCamp/blob/main/Torch_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Backpropagation

In [ ]:
import torch
x = torch.ones((2,2), requires_grad =True)
y = x + 2
z = 2 * y * y
out = z.mean()

In [ ]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
torch.cuda.is_available()

True

In [ ]:
# A 1-D Tensor
x = torch.tensor([2,2,1])
print(x)

tensor([2, 2, 1])


In [ ]:
# A 2-D Tensor
y = torch.tensor([[2,1,8],[9,5,6],[1,2,9],[6,3,2]])
print(y)

tensor([[2, 1, 8],
        [9, 5, 6],
        [1, 2, 9],
        [6, 3, 2]])


How to print the size and shape of tensors

In [ ]:
#The size of the tensors
print(x.shape)
print(y.shape)
print(x.size())
print(y.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [ ]:
#et the height/number of rows of y
#to get the rows of y
print(y.shape[0])

4


In [ ]:
# How to define a Float Tensor
a = torch.FloatTensor([[3,1,4],[3,5,7],[4,8,0],[7,9,2]])

In [ ]:
# How to define a double Tensor
b = torch.DoubleTensor([[2,1,4],[5,5,4],[1,2,9],[7,3,2]])

In [ ]:
# how to check for datatype
print(a)
print(a.dtype)

tensor([[3., 1., 4.],
        [3., 5., 7.],
        [4., 8., 0.],
        [7., 9., 2.]])
torch.float32


In [ ]:
print(b)
print(b.dtype) # b datatype

tensor([[2., 1., 4.],
        [5., 5., 4.],
        [1., 2., 9.],
        [7., 3., 2.]], dtype=torch.float64)
torch.float64


In [ ]:
print(a.mean())

tensor(4.4167)


In [ ]:
print(b.mean())

tensor(3.7500, dtype=torch.float64)


In [ ]:
print(a.std())

tensor(2.8431)


In [ ]:
print(b.std())

tensor(2.4541, dtype=torch.float64)


AutoGrad

In [ ]:
#Remember, If requires_grad=True, the Tensor object keeps track of how it was created.
x = torch.tensor([10., 25., 35], requires_grad=True)
y = torch.tensor([40., 5., 60], requires_grad=True)
#Notice that both x and y have their required_grad set to true, therefore we an compute gradients with respect to them
z = x + y
print(z)
# z knows that is was created as a result of addition of x and y. It knows that it wasn't read in from a file
print(z.grad_fn)
#And if we go further on this
s = z.sum()
print(s)
print(s.grad_fn)

tensor([50., 30., 95.], grad_fn=<AddBackward0>)
tensor(175., grad_fn=<SumBackward0>)
